language: node_js
node_js:
  - "10"
  - "12"
  - "14"

# Workaround for Travis not being able to fetch ssh urls.
#
# https://stackoverflow.com/a/24600210 and https://gist.github.com/iedemam/9830045
#

# disable the default submodule logic
git:
  submodules: false

# use sed to replace the SSH URL with the public URL, then init and update submodules
before_install:
 - sed -i 's/git@github.com:/git:\/\/github.com\//' .gitmodules
 - git submodule update --init --recursive
